# Autogenerated file, do not write.

def python_add(n_clicks, label):
    if not n_clicks:
        return 1
    return int(label) + 1

def python_substract(n_clicks, label):
    if not n_clicks:
        return 1
    return int(label) - 1

